# Generated by Django 4.0.4 on 2022-05-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CATI',
            new_name='CATImg',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='PRDIImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صور المنتج'),
        ),
    ]
