# Generated by Django 4.0.4 on 2022-05-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_prdcategory_product_prdprand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صور المنتج'),
        ),
    ]
