# Generated by Django 4.0.4 on 2022-06-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_prdslug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDIName', models.CharField(max_length=600, verbose_name='اسم صاحب التعليق')),
                ('PRDICommands', models.TextField(max_length=600, verbose_name='التعليق')),
                ('PRDIPriority', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='التقييم')),
                ('PRDItitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='التعليقات على المنتج')),
            ],
        ),
    ]
