# Generated by Django 4.0.4 on 2022-06-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_commandspost_prdipriority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommandsPost',
        ),
    ]
