# Generated by Django 4.0.4 on 2022-06-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_commandspost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommandsPost',
        ),
    ]
