# Generated by Django 4.0.4 on 2022-06-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_delete_commandspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDImage1',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='1صور المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDImage2',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='2صور المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDImage3',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='3صور المنتج'),
        ),
    ]
