# Generated by Django 4.0.4 on 2022-06-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_rename_prdimage_product_prdsimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PRDSImage',
            new_name='PRDImage',
        ),
    ]
