# Generated by Django 4.0.4 on 2022-06-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_rename_prdsimage_product_prdimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDSImage1',
            field=models.ImageField(blank=True, null=True, upload_to='products1/', verbose_name='1صور صغيرة للمنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDSImage2',
            field=models.ImageField(blank=True, null=True, upload_to='products2/', verbose_name='2صور صغيرة للمنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDSImage3',
            field=models.ImageField(blank=True, null=True, upload_to='products3/', verbose_name='3صور صغيرة للمنتج'),
        ),
    ]
